require "biblio_refs/version"
require "biblio_refs/referencia"
require "biblio_refs/list"
require "biblio_refs/libro"
require "biblio_refs/publicacion_periodica"
require "biblio_refs/revista"
require "biblio_refs/articulo_periodico"
require "biblio_refs/documento_electronico"